### ISSUE TITLE
关于论文中错误类型判断的几个问题

### ISSUE THREAD

**Issue by tjscooney** [THUKElab/DR-CSC#1]
作者，你好。我看了你的论文，感觉这个工作对我很有帮助。并且我有以下几个疑问：①论文中会判断错误类型是音近错误还是形近错误，在代码中是在哪个部分实现的呢②训练集中的mid_labels标签的具体作用是什么。望作者能帮我解答一下疑惑，谢谢。

**Comment by waterwaterrr** [comment]
①论文中判断音近形近的方式是根据音近形近的混淆集进行查表，在代码中https://github.com/THUKElab/DR-CSC/blob/main/src/models.py#L408C17-L414C61
②代码中的low, mid, high对应论文中的Detection, Reasoning, Searching，即mid_labels为每个字的错误类别（正确的字也被标注了类别但是在后续是用不上的），mid_labels是用训练集查表得到的

**Comment by tjscooney** [comment]
mid_labels中每个字的错误类别指的是什么呢，如1是什么，0是什么。其次为啥mid_labels这个数组的元素个数与字符串从长度并不相等呢？望作者能帮我解答一下疑惑，谢谢。

**Comment by waterwaterrr** [comment]
mid_labels中错误类型可以在这个if-else中看到https://github.com/THUKElab/DR-CSC/blob/main/src/models.py#L411C21-L414C61：
在处理mid_label的时候，由于文本输入BERT编码时会产生[CLS], [SEP]，所以为了后续对齐长度的方便，mid_labels就会比句子长度多2，所以mid_labels中间部分去头去尾中间部分才是有效部分。这点为本人代码实现经验上不足造成误解，感到抱歉。

**Comment by tjscooney** [comment]
好的好的，谢谢作者
