### ISSUE TITLE
关于transfer_data的疑问

### ISSUE THREAD

**Issue by Liucc2119** [THUKElab/DR-CSC#2]
您好，看了您的代码后我有一个疑问，代码中的transfer_data是指的哪种类型的数据？以及transfer_data的数据格式是什么样子的为什么这样处理transfer_data呢？
self.transfer_data = f.read().split('\n')
                self.transfer_data = [line.split(', ') for line in self.transfer_data]

**Comment by waterwaterrr** [comment]
下面是一个例子：
```
A2-0011-1, 0
A2-0023-1, 10, 唷, 形
A2-0023-2, 0
A2-0029-1, 3, 气, 音
……
A2-0061-1, 4, 菜, 形, 7, 他, 形
……
```
每行数据对应一个句子，分别代表``id, typo_index, typo_character, typo_type``，如果句子中有多个错别字，则接着拼接`` typo_index, typo_character, typo_type``
