### ISSUE TITLE
尊敬的作者，为什么训练损失函数一直在100左右降不下来？

### ISSUE THREAD

**Issue by SuperLumi-tech** [THUKElab/DR-CSC#6]
![image](https://github.com/THUKElab/DR-CSC/assets/127109559/899bb4dd-1011-45dd-b5db-55f28a430b59)

**Comment by SuperLumi-tech** [comment]
![image](https://github.com/THUKElab/DR-CSC/assets/127109559/e0de672c-65de-4db9-92e6-b17396a6def1)

**Comment by waterwaterrr** [comment]
因为加上了detection和reasoning这部分比较难训练，总体loss会高
